import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  weight: ["500", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Result Summary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon/icon.png" sizes="32x32" type="image/png" />
      </head>
      <body
        className={`${hankenGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
